language: python
python:
  - "2.7"

before_install:
  - sudo apt-get -y install python-pip python-dev
install:
  - pip install --use-mirrors numpy nose flake8 coveralls
  - pip install --use-mirrors scipy patsy
  - pip install --use-mirrors -r requirements.txt

before_script:
  - flake8 insights tests
script:
  - nosetests -w tests --with-coverage --cover-package=insights

after_success:
  - coveralls

branches:
  only:
    - master
    - develop
