language: python
python:
  - "2.7"

before_install:
  - sudo apt-get -y install python-pip python-dev g++ make libfreetype6-dev libpng-dev libopenblas-dev liblapack-dev gfortran r-base
install:
  - pip install --use-mirrors numpy nose flake8 coveralls
  - pip install -e git+https://github.com/hackliff/intuition.git@develop#egg=intuition
  - pip install --use-mirrors -r requirements.txt

before_script:
  - flake8 insights tests
script:
  - nosetests -w tests --with-coverage --cover-package=insights

after_success:
  - coveralls

branches:
  only:
    - master
    - develop
